<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IngredientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("ingredients")->insert(
            [
			['id' => 1,'name' => 'Cream cheese','category_id' => 1],
			['id' => 2,'name' => 'Sour cream','category_id' => 1],
			['id' => 3,'name' => 'Mayonnaise','category_id' => 2],
			['id' => 4,'name' => 'Mozzarella','category_id' => 1],
			['id' => 5,'name' => 'Spinach','category_id' => 3],
			['id' => 6,'name' => 'Artichokes','category_id' => 3],
			['id' => 7,'name' => 'Garlic','category_id' => 4],
			['id' => 8,'name' => 'Pepper','category_id' => 4],
			['id' => 9,'name' => 'Salt','category_id' => 4],
			['id' => 10,'name' => 'Mushroom','category_id' => 3],
			['id' => 11,'name' => 'Shallot','category_id' => 3],
			['id' => 12,'name' => 'Unsmoked bacon lardons','category_id' => 5],
			['id' => 13,'name' => 'Breadcrumbs','category_id' => 6],
			['id' => 14,'name' => 'Dried sage','category_id' => 4],
			['id' => 15,'name' => 'Cheddar cheese','category_id' => 1],
			['id' => 16,'name' => 'Tomatoes','category_id' => 3],
			['id' => 17,'name' => 'Basil','category_id' => 3],
			['id' => 18,'name' => 'Crushed red pepper','category_id' => 3],
			['id' => 19,'name' => 'Extra-virgin olive oil','category_id' => 7],
			['id' => 20,'name' => 'Balsamic vinegar','category_id' => 8],
			['id' => 21,'name' => 'Kosher salt','category_id' => 4],
			['id' => 22,'name' => 'Baguette','category_id' => 6],
			['id' => 23,'name' => 'Egg','category_id' => 9],
			['id' => 24,'name' => 'Yellow mustard','category_id' => 2],
			['id' => 25,'name' => 'Black pepper','category_id' => 4],
			['id' => 26,'name' => 'Smoked Spanish paprika','category_id' => 4],
			['id' => 27,'name' => 'white vinegar','category_id' => 8],
			['id' => 28,'name' => 'Brie','category_id' => 1],
			['id' => 29,'name' => 'Thyme leaf','category_id' => 4],
			['id' => 30,'name' => 'Rosemary leaf','category_id' => 4],
			['id' => 31,'name' => 'Honey','category_id' => 10],
			['id' => 32,'name' => 'Chicken wing','category_id' => 5],
			['id' => 33,'name' => 'Vegetable oil','category_id' => 7],
			['id' => 34,'name' => 'Garlic powder','category_id' => 4],
			['id' => 35,'name' => 'Hot sauce','category_id' => 2],
			['id' => 36,'name' => 'Butter','category_id' => 1],
			['id' => 37,'name' => 'Parmesan','category_id' => 1],
			['id' => 38,'name' => 'Avocado ','category_id' => 11],
			['id' => 39,'name' => 'Lime','category_id' => 11],
			['id' => 40,'name' => 'Onion','category_id' => 3],
			['id' => 41,'name' => 'Cilantro','category_id' => 4],
			['id' => 42,'name' => 'Cayenne pepper','category_id' => 4],
			['id' => 43,'name' => 'Chickpeas','category_id' => 3],
			['id' => 44,'name' => 'Water','category_id' => 12],
			['id' => 45,'name' => 'Lemon juice','category_id' => 12],
			['id' => 46,'name' => 'Sea salt','category_id' => 4],
			['id' => 47,'name' => 'Tahini','category_id' => 4],
			['id' => 48,'name' => 'Olive oil','category_id' => 7],
			['id' => 49,'name' => 'Lemon zest','category_id' => 11],
			['id' => 50,'name' => 'Ice','category_id' => 13],
			['id' => 51,'name' => 'Granulated sugar','category_id' => 10],
			['id' => 52,'name' => 'Parsley','category_id' => 4],
			['id' => 53,'name' => 'Shrimp','category_id' => 14],
			['id' => 54,'name' => 'Chili sauce','category_id' => 2],
			['id' => 55,'name' => 'Ketchup','category_id' => 2],
			['id' => 56,'name' => 'Horseradish','category_id' => 3],
			['id' => 57,'name' => 'Worcestershire sauce','category_id' => 2],
			['id' => 58,'name' => 'Celery salt','category_id' => 4],
			['id' => 59,'name' => 'Carrot','category_id' => 3],
			['id' => 60,'name' => 'Celery','category_id' => 3],
			['id' => 61,'name' => 'Tomato purée','category_id' => 15],
			['id' => 62,'name' => 'Bay leaf','category_id' => 4],
			['id' => 63,'name' => 'Stock-cube','category_id' => 4],
			['id' => 64,'name' => 'Unsalted butter','category_id' => 1],
			['id' => 65,'name' => 'Celery ribs','category_id' => 3],
			['id' => 66,'name' => 'Chicken breast','category_id' => 5],
			['id' => 67,'name' => 'Egg noodles','category_id' => 16],
			['id' => 68,'name' => 'Parsley leaf','category_id' => 4],
			['id' => 69,'name' => 'Dill','category_id' => 4],
			['id' => 70,'name' => 'Flour','category_id' => 17],
			['id' => 71,'name' => 'White wine','category_id' => 19],
			['id' => 72,'name' => 'Beef Stock-cube','category_id' => 4],
			['id' => 73,'name' => 'Gruyère','category_id' => 1],
			['id' => 74,'name' => 'Celery stick','category_id' => 3],
			['id' => 75,'name' => 'Courgette','category_id' => 3],
			['id' => 76,'name' => 'Smoked pancetta','category_id' => 5],
			['id' => 77,'name' => 'Dried oregano','category_id' => 4],
			['id' => 78,'name' => 'Cannellini beans','category_id' => 15],
            ['id' => 79,'name' => 'Ground pepper', 'category_id' => 4],
			['id' => 80,'name' => 'Vegetable stock','category_id' => 12],
			['id' => 81,'name' => 'Small pasta','category_id' => 16],
			['id' => 82,'name' => 'Kale','category_id' => 3],
			['id' => 83,'name' => 'Chard ','category_id' => 3],
			['id' => 84,'name' => 'All-purpose flour','category_id' => 17],
			['id' => 85,'name' => 'Chicken broth','category_id' => 12],
			['id' => 86,'name' => 'Broccoli','category_id' => 3],
			['id' => 87,'name' => 'Heavy cream','category_id' => 1],
			['id' => 88,'name' => 'Coarse salt','category_id' => 4],
			['id' => 89,'name' => 'Potatoes','category_id' => 3],
			['id' => 90,'name' => 'Minced clams','category_id' => 15],
			['id' => 91,'name' => 'Cream','category_id' => 1],
			['id' => 92,'name' => 'Red wine vinegar','category_id' => 8],
			['id' => 93,'name' => 'Dried split peas','category_id' => 3],
			['id' => 94,'name' => 'Ham bone','category_id' => 18],
			['id' => 95,'name' => 'Cucumber, ','category_id' => 3],
			['id' => 96,'name' => 'Red bell pepper','category_id' => 3],
			['id' => 97,'name' => 'Sherry vinegar','category_id' => 8],
			['id' => 98,'name' => 'Country bread','category_id' => 6],
			['id' => 99,'name' => 'Dry lentils','category_id' => 3],
			['id' => 100,'name' => 'Crushed tomatoes','category_id' => 15],
			['id' => 101,'name' => 'Beef stewing meat','category_id' => 5],
			['id' => 102,'name' => 'Red wine','category_id' => 19],
			['id' => 103,'name' => 'Beef broth','category_id' => 12],
			['id' => 104,'name' => 'Italian sausage','category_id' => 5],
			['id' => 105,'name' => 'Ground beef','category_id' => 5],
			['id' => 106,'name' => 'Tomato sauce','category_id' => 15],
			['id' => 107,'name' => 'Tomato paste','category_id' => 15],
			['id' => 108,'name' => 'Fennel','category_id' => 4],
			['id' => 109,'name' => 'Lasagna noodles','category_id' => 16],
			['id' => 110,'name' => 'Ricotta cheese','category_id' => 1],
			['id' => 112,'name' => 'Provolone cheese','category_id' => 1],
			['id' => 113,'name' => 'Pork chops bone in','category_id' => 5],
			['id' => 114,'name' => 'Rice wine vinegar','category_id' => 8],
			['id' => 116,'name' => 'Fillet steak','category_id' => 5],
			['id' => 117,'name' => 'Crème fraîche','category_id' => 2],
			['id' => 118,'name' => 'English mustard','category_id' => 2],
			['id' => 119,'name' => 'Beef stock','category_id' => 12],
			['id' => 120,'name' => 'Chili powder','category_id' => 4],
			['id' => 121,'name' => 'Ground cumin','category_id' => 4],
			['id' => 122,'name' => 'Taco shells','category_id' => 16],
			['id' => 123,'name' => 'Salmon fillets','category_id' => 14],
			['id' => 124,'name' => 'Salmon','category_id' => 14],
			['id' => 125,'name' => 'Grape seed oil','category_id' => 7],
			['id' => 126,'name' => 'Beef sirloin','category_id' => 5],
			['id' => 127,'name' => 'Green onion','category_id' => 3],
			['id' => 128,'name' => 'Soy sauce','category_id' => 2],
			['id' => 129,'name' => 'Sesame seed','category_id' => 4],
			['id' => 130,'name' => 'Smoked streaky bacon','category_id' => 15],
			['id' => 131,'name' => 'Minced beef','category_id' => 5],
			['id' => 132,'name' => 'Sun-dried tomatoes','category_id' => 20],
			['id' => 133,'name' => 'Plum tomatoes','category_id' => 15],
			['id' => 134,'name' => 'Dried spaghetti','category_id' => 16],
			['id' => 135,'name' => 'Frozen peas','category_id' => 3],
			['id' => 136,'name' => 'Rice','category_id' => 17],
			['id' => 137,'name' => 'Oyster sauce','category_id' => 2],
			['id' => 138,'name' => 'Toasted sesame oil','category_id' => 7],
			['id' => 139,'name' => 'Bramley apple','category_id' => 11],
			['id' => 140,'name' => 'Golden caster sugar','category_id' => 10],
			['id' => 141,'name' => 'Cinnamon','category_id' => 4],
			['id' => 142,'name' => 'Unsweetened cocoa powder','category_id' => 21],
			['id' => 143,'name' => 'Baking soda','category_id' => 22],
			['id' => 144,'name' => 'Baking powder','category_id' => 22],
			['id' => 145,'name' => 'Buttermilk','category_id' => 1],
			['id' => 146,'name' => 'Warm water','category_id' => 12],
			['id' => 147,'name' => 'Vanilla extract','category_id' => 23],
			['id' => 148,'name' => 'Strawberry','category_id' => 11],
			['id' => 149,'name' => 'Whipped cream','category_id' => 1],
			['id' => 150,'name' => 'Cocoa powder','category_id' => 21],
			['id' => 151,'name' => 'Dark chocolate','category_id' => 1],
			['id' => 152,'name' => 'Chocolate','category_id' => 1],
			['id' => 153,'name' => 'Vanilla','category_id' => 23],
			['id' => 154,'name' => 'Bananas','category_id' => 11],
			['id' => 155,'name' => 'Chocolate chips','category_id' => 1],
			['id' => 156,'name' => 'Pie crust','category_id' => 16],
			['id' => 157,'name' => 'Pecan','category_id' => 11],
			['id' => 158,'name' => 'Corn syrup','category_id' => 10],
			['id' => 159,'name' => 'Brown sugar','category_id' => 10],
			['id' => 160,'name' => 'Molasses','category_id' => 10],
			['id' => 161,'name' => 'Blueberry, ','category_id' => 11],
			['id' => 162,'name' => 'Cornstarch','category_id' => 1],
			['id' => 163,'name' => 'Tapioca','category_id' => 17],
			['id' => 164,'name' => 'Milk','category_id' => 1],
			['id' => 165,'name' => 'Natural yogurt','category_id' => 1],
			['id' => 166,'name' => 'Self-raising flour','category_id' => 1],
			['id' => 167,'name' => 'Muscovado sugar','category_id' => 10],
			['id' => 168,'name' => 'Nutmeg','category_id' => 4],
			['id' => 169,'name' => 'Raisin','category_id' => 11],
			['id' => 170,'name' => 'Walnut','category_id' => 24],
			['id' => 171,'name' => 'Icing sugar','category_id' => 10],
			['id' => 172,'name' => 'Soft cheese','category_id' => 1],
			['id' => 173,'name' => 'Cracker crumbs','category_id' => 6],
            ['id' => 174,'name' => 'Lemon', 'category_id' => 11],
            ['id' => 175,'name' => 'Chicken stock', 'category_id' => 12],
            ['id' => 176,'name' => 'Vinegar', 'category_id' => 8],
			['id' => 177,'name' => 'Italian seasoning','category_id' => 23],
			['id' => 178,'name' => 'Orange','category_id' => 11]
            ]);
    }
}
