<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IngredientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("ingredients")->insert(
            [
			['id' => 1,'name' => 'Cream cheese','category' => 'Dairy'],
			['id' => 2,'name' => 'Sour cream','category' => 'Dairy'],
			['id' => 3,'name' => 'Mayonnaise','category' => 'Sauce'],
			['id' => 4,'name' => 'Mozzarella','category' => 'Dairy'],
			['id' => 5,'name' => 'Spinach','category' => 'Vegetable'],
			['id' => 6,'name' => 'Artichokes','category' => 'Vegetable'],
			['id' => 7,'name' => 'Garlic','category' => 'Spice'],
			['id' => 8,'name' => 'Pepper','category' => 'Spice'],
			['id' => 9,'name' => 'Salt','category' => 'Spice'],
			['id' => 10,'name' => 'Mushroom','category' => 'Vegetable'],
			['id' => 11,'name' => 'Shallot','category' => 'Vegetable'],
			['id' => 12,'name' => 'Unsmoked bacon lardons','category' => 'Meat'],
			['id' => 13,'name' => 'dried breadcrumbs','category' => 'Bakery'],
			['id' => 14,'name' => 'Dried sage','category' => 'Spice'],
			['id' => 15,'name' => 'Cheddar cheese','category' => 'Dairy'],
			['id' => 16,'name' => 'Tomatoes','category' => 'Vegetable'],
			['id' => 17,'name' => 'Basil','category' => 'Vegetable'],
			['id' => 18,'name' => 'Crushed red pepper','category' => 'Vegetable'],
			['id' => 19,'name' => 'Extra-virgin olive oil','category' => 'Oil'],
			['id' => 20,'name' => 'Balsamic vinegar','category' => 'Vinegar'],
			['id' => 21,'name' => 'Kosher salt','category' => 'Spice'],
			['id' => 22,'name' => 'Baguette','category' => 'Bakery'],
			['id' => 23,'name' => 'Egg','category' => 'Protein'],
			['id' => 24,'name' => 'Yellow mustard','category' => 'Sauce'],
			['id' => 25,'name' => 'Black pepper','category' => 'Spice'],
			['id' => 26,'name' => 'Smoked Spanish paprika','category' => 'Spice'],
			['id' => 27,'name' => 'white vinegar','category' => 'Vinegar'],
			['id' => 28,'name' => 'Brie','category' => 'Dairy'],
			['id' => 29,'name' => 'Thyme leaf','category' => 'Spice'],
			['id' => 30,'name' => 'Rosemary leaf','category' => 'Spice'],
			['id' => 31,'name' => 'Honey','category' => 'Sweetener'],
			['id' => 32,'name' => 'Chicken wing','category' => 'Meat'],
			['id' => 33,'name' => 'Vegetable oil','category' => 'Oil'],
			['id' => 34,'name' => 'Garlic powder','category' => 'Spice'],
			['id' => 35,'name' => 'Hot sauce','category' => 'Sauce'],
			['id' => 36,'name' => 'Butter','category' => 'Dairy'],
			['id' => 37,'name' => 'Parmesan','category' => 'Dairy'],
			['id' => 38,'name' => 'Avocado ','category' => 'Fruit'],
			['id' => 39,'name' => 'Lime','category' => 'Fruit'],
			['id' => 40,'name' => 'Onion','category' => 'Vegetable'],
			['id' => 41,'name' => 'Cilantro','category' => 'Spice'],
			['id' => 42,'name' => 'Cayenne pepper','category' => 'Spice'],
			['id' => 43,'name' => 'Chickpeas','category' => 'Vegetable'],
			['id' => 44,'name' => 'Water','category' => 'Liquid'],
			['id' => 45,'name' => 'Lemon juice','category' => 'Liquid'],
			['id' => 46,'name' => 'Sea salt','category' => 'Spice'],
			['id' => 47,'name' => 'Tahini','category' => 'Spice'],
			['id' => 48,'name' => 'Olive oil','category' => 'Oil'],
			['id' => 49,'name' => 'Lemon zest','category' => 'Fruit'],
			['id' => 50,'name' => 'Ice','category' => 'Ice'],
			['id' => 51,'name' => 'Granulated sugar','category' => 'Sweetener'],
			['id' => 52,'name' => 'Parsley','category' => 'Spice'],
			['id' => 53,'name' => 'Shrimp','category' => 'Seafood'],
			['id' => 54,'name' => 'Chili sauce','category' => 'sauce'],
			['id' => 55,'name' => 'Ketchup','category' => 'sauce'],
			['id' => 56,'name' => 'Horseradish','category' => 'Vegetable'],
			['id' => 57,'name' => 'Worcestershire sauce','category' => 'sauce'],
			['id' => 58,'name' => 'Celery salt','category' => 'Spice'],
			['id' => 59,'name' => 'Carrot','category' => 'Vegetable'],
			['id' => 60,'name' => 'Celery','category' => 'Vegetable'],
			['id' => 61,'name' => 'Tomato purée','category' => 'Can'],
			['id' => 62,'name' => 'Bay leaf','category' => 'Spice'],
			['id' => 63,'name' => 'Stock-cube','category' => 'Spice'],
			['id' => 64,'name' => 'Unsalted butter','category' => 'Dairy'],
			['id' => 65,'name' => 'Celery ribs','category' => 'Vegetable'],
			['id' => 66,'name' => 'Chicken breast','category' => 'Meat'],
			['id' => 67,'name' => 'Egg noodles','category' => 'Pasta'],
			['id' => 68,'name' => 'Parsley leaf','category' => 'Spice'],
			['id' => 69,'name' => 'Dill','category' => 'Spice'],
			['id' => 70,'name' => 'Flour','category' => 'Grain'],
			['id' => 71,'name' => 'White wine','category' => 'Wine'],
			['id' => 72,'name' => 'Beef Stock-cube','category' => 'Spice'],
			['id' => 73,'name' => 'Gruyère','category' => 'Dairy'],
			['id' => 74,'name' => 'Celery stick','category' => 'Vegetable'],
			['id' => 75,'name' => 'Courgette','category' => 'Vegetable'],
			['id' => 76,'name' => 'Smoked pancetta','category' => 'Meat'],
			['id' => 77,'name' => 'Dried oregano','category' => 'Spice'],
			['id' => 78,'name' => 'Cannellini beans','category' => 'Can'],
            ['id' => 79,'name' => 'Ground pepper', 'category' => 'Spice'],
			['id' => 80,'name' => 'Vegetable stock','category' => 'Liquid'],
			['id' => 81,'name' => 'Small pasta','category' => 'Pasta'],
			['id' => 82,'name' => 'Kale','category' => 'Vegetable'],
			['id' => 83,'name' => 'Chard ','category' => 'Vegetable'],
			['id' => 84,'name' => 'All-purpose flour','category' => 'Grain'],
			['id' => 85,'name' => 'Chicken broth','category' => 'Liquid'],
			['id' => 86,'name' => 'Broccoli','category' => 'Vegetable'],
			['id' => 87,'name' => 'Heavy cream','category' => 'Dairy'],
			['id' => 88,'name' => 'Coarse salt','category' => 'Spice'],
			['id' => 89,'name' => 'Potatoes','category' => 'Vegetable'],
			['id' => 90,'name' => 'Minced clams','category' => 'Can'],
			['id' => 91,'name' => 'Cream','category' => 'Dairy'],
			['id' => 92,'name' => 'Red wine vinegar','category' => 'Vinegar'],
			['id' => 93,'name' => 'Dried split peas','category' => 'Vegetable'],
			['id' => 94,'name' => 'Ham bone','category' => 'Other'],
			['id' => 95,'name' => 'Cucumber, ','category' => 'Vegetable'],
			['id' => 96,'name' => 'Red bell pepper','category' => 'Vegetable'],
			['id' => 97,'name' => 'Sherry vinegar','category' => 'Vinegar'],
			['id' => 98,'name' => 'Country bread','category' => 'Bakery'],
			['id' => 99,'name' => 'Dry lentils','category' => 'Vegetable'],
			['id' => 100,'name' => 'Crushed tomatoes','category' => 'Can'],
			['id' => 101,'name' => 'Beef stewing meat','category' => 'Meat'],
			['id' => 102,'name' => 'Red wine','category' => 'Wine'],
			['id' => 103,'name' => 'Beef broth','category' => 'Liquid'],
			['id' => 104,'name' => 'Italian sausage','category' => 'Meat'],
			['id' => 105,'name' => 'Ground beef','category' => 'Meat'],
			['id' => 106,'name' => 'Tomato sauce','category' => 'Can'],
			['id' => 107,'name' => 'Tomato paste','category' => 'Can'],
			['id' => 108,'name' => 'Fennel','category' => 'Spice'],
			['id' => 109,'name' => 'Lasagna noodles','category' => 'Pasta'],
			['id' => 110,'name' => 'Ricotta cheese','category' => 'Dairy'],
			['id' => 111,'name' => 'Bread crumbs','category' => 'Bakery'],
			['id' => 112,'name' => 'Provolone cheese','category' => 'Dairy'],
			['id' => 113,'name' => 'Pork chops bone in','category' => 'Meat'],
			['id' => 114,'name' => 'Rice wine vinegar','category' => 'Vinegar'],
			['id' => 115,'name' => 'Mushroom','category' => 'Vegetable'],
			['id' => 116,'name' => 'Fillet steak','category' => 'Meat'],
			['id' => 117,'name' => 'Crème fraîche','category' => 'Sauce'],
			['id' => 118,'name' => 'English mustard','category' => 'Sauce'],
			['id' => 119,'name' => 'Beef stock','category' => 'Liquid'],
			['id' => 120,'name' => 'Chili powder','category' => 'Spice'],
			['id' => 121,'name' => 'Ground cumin','category' => 'Spice'],
			['id' => 122,'name' => 'Taco shells','category' => 'pasta'],
			['id' => 123,'name' => 'Salmon fillets','category' => 'Seafood'],
			['id' => 124,'name' => 'Salmon','category' => 'Seafood'],
			['id' => 125,'name' => 'Grape seed oil','category' => 'Oil'],
			['id' => 126,'name' => 'Beef sirloin','category' => 'Meat'],
			['id' => 127,'name' => 'Green onion','category' => 'Vegetable'],
			['id' => 128,'name' => 'Soy sauce','category' => 'sauce'],
			['id' => 129,'name' => 'Sesame seed','category' => 'spice'],
			['id' => 130,'name' => 'Smoked streaky bacon','category' => 'Can'],
			['id' => 131,'name' => 'Minced beef','category' => 'Meat'],
			['id' => 132,'name' => 'Sun-dried tomatoes','category' => 'Jar'],
			['id' => 133,'name' => 'Plum tomatoes','category' => 'Tin'],
			['id' => 134,'name' => 'Dried spaghetti','category' => 'Pasta'],
			['id' => 135,'name' => 'Frozen peas','category' => 'Vegetable'],
			['id' => 136,'name' => 'Rice','category' => 'Grain'],
			['id' => 137,'name' => 'Oyster sauce','category' => 'sauce'],
			['id' => 138,'name' => 'Toasted sesame oil','category' => 'oil'],
			['id' => 139,'name' => 'Bramley apple','category' => 'Fruit'],
			['id' => 140,'name' => 'Golden caster sugar','category' => 'Sweetener'],
			['id' => 141,'name' => 'Cinnamon','category' => 'Spice'],
			['id' => 142,'name' => 'Unsweetened cocoa powder','category' => 'Flavor enhancer'],
			['id' => 143,'name' => 'Baking soda','category' => 'Leavening agent'],
			['id' => 144,'name' => 'Baking powder','category' => 'Leavening agent'],
			['id' => 145,'name' => 'Buttermilk','category' => 'Dairy '],
			['id' => 146,'name' => 'Warm water','category' => 'Liquid'],
			['id' => 147,'name' => 'Vanilla extract','category' => 'Seasoning'],
			['id' => 148,'name' => 'Strawberry','category' => 'Fruit'],
			['id' => 149,'name' => 'Whipped cream','category' => 'Dairy'],
			['id' => 150,'name' => 'Cocoa powder','category' => 'Flavor enhancer'],
			['id' => 151,'name' => 'Dark chocolate','category' => 'Dairy'],
			['id' => 152,'name' => 'Chocolate','category' => 'Dairy'],
			['id' => 153,'name' => 'Vanilla','category' => 'Seasoning'],
			['id' => 154,'name' => 'Bananas','category' => 'Fruit'],
			['id' => 155,'name' => 'Chocolate chips','category' => 'Dairy'],
			['id' => 156,'name' => 'Pie crust','category' => 'Pasta'],
			['id' => 157,'name' => 'Pecan','category' => 'Fruit'],
			['id' => 158,'name' => 'Corn syrup','category' => 'Sweetener'],
			['id' => 159,'name' => 'Brown sugar','category' => 'Sweetener'],
			['id' => 160,'name' => 'Molasses','category' => 'Sweetener'],
			['id' => 161,'name' => 'Blueberry, ','category' => 'Fruit'],
			['id' => 162,'name' => 'Cornstarch','category' => 'Dairy'],
			['id' => 163,'name' => 'Tapioca','category' => 'Grain'],
			['id' => 164,'name' => 'Milk','category' => 'Dairy'],
			['id' => 165,'name' => 'Natural yogurt','category' => 'Dairy'],
			['id' => 166,'name' => 'Self-raising flour','category' => 'Dairy'],
			['id' => 167,'name' => 'Muscovado sugar','category' => 'Sweetener'],
			['id' => 168,'name' => 'Nutmeg','category' => 'spice'],
			['id' => 169,'name' => 'Raisin','category' => 'Dried fruit'],
			['id' => 170,'name' => 'Walnut','category' => 'Nut'],
			['id' => 171,'name' => 'Icing sugar','category' => 'Sweetener'],
			['id' => 172,'name' => 'Soft cheese','category' => 'Dairy'],
			['id' => 173,'name' => 'Cracker crumbs','category' => 'Bakery'],
            ['id' => 174,'name' => 'Lemon', 'category' => 'Fruit'],
            ['id' => 175,'name' => 'Chicken stock', 'category' => 'Liquid'],
            ['id' => 176,'name' => 'Vinegar', 'category' => 'Vinegar']
            ]);
    }
}
