<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ValidMeasureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('valid_measures')->insert([
            [ 'measure_id' => 11, 'ingredient_id' => 1],
            [ 'measure_id' => 12, 'ingredient_id' => 1],
            [ 'measure_id' => 17, 'ingredient_id' => 1],
            [ 'measure_id' => 15, 'ingredient_id' => 1],
            [ 'measure_id' => 20, 'ingredient_id' => 1],

            [ 'measure_id' => 11, 'ingredient_id' => 2],
            [ 'measure_id' => 12, 'ingredient_id' => 2],
            [ 'measure_id' => 13, 'ingredient_id' => 2],
            [ 'measure_id' => 14, 'ingredient_id' => 2],
            [ 'measure_id' => 15, 'ingredient_id' => 2],
            [ 'measure_id' => 1, 'ingredient_id' => 2],
            [ 'measure_id' => 2, 'ingredient_id' => 2],

            [ 'measure_id' => 11, 'ingredient_id' => 3],
            [ 'measure_id' => 12, 'ingredient_id' => 3],
            [ 'measure_id' => 15, 'ingredient_id' => 3],
            [ 'measure_id' => 1, 'ingredient_id' => 3],
            [ 'measure_id' => 2, 'ingredient_id' => 3],

            [ 'measure_id' => 11, 'ingredient_id' => 4],
            [ 'measure_id' => 12, 'ingredient_id' => 4],
            [ 'measure_id' => 15, 'ingredient_id' => 4],
            [ 'measure_id' => 17, 'ingredient_id' => 4],

            [ 'measure_id' => 11, 'ingredient_id' => 5],
            [ 'measure_id' => 12, 'ingredient_id' => 5],
            [ 'measure_id' => 17, 'ingredient_id' => 5],
            [ 'measure_id' => 15, 'ingredient_id' => 5],

            [ 'measure_id' => 11, 'ingredient_id' => 6],
            [ 'measure_id' => 12, 'ingredient_id' => 6],
            [ 'measure_id' => 15, 'ingredient_id' => 6],
            [ 'measure_id' => 17, 'ingredient_id' => 6],

            [ 'measure_id' => 11, 'ingredient_id' => 7],
            [ 'measure_id' => 12, 'ingredient_id' => 7],
            [ 'measure_id' => 15, 'ingredient_id' => 7],
            [ 'measure_id' => 17, 'ingredient_id' => 7],

            [ 'measure_id' => 11, 'ingredient_id' => 8],
            [ 'measure_id' => 12, 'ingredient_id' => 8],
            [ 'measure_id' => 15, 'ingredient_id' => 8],
            [ 'measure_id' => 16, 'ingredient_id' => 8],
            [ 'measure_id' => 1, 'ingredient_id' => 8],
            [ 'measure_id' => 2, 'ingredient_id' => 8],
            [ 'measure_id' => 18, 'ingredient_id' => 8],
            [ 'measure_id' => 19, 'ingredient_id' => 8],

            [ 'measure_id' => 11, 'ingredient_id' => 9],
            [ 'measure_id' => 12, 'ingredient_id' => 9],
            [ 'measure_id' => 15, 'ingredient_id' => 9],
            [ 'measure_id' => 16, 'ingredient_id' => 9],
            [ 'measure_id' => 1, 'ingredient_id' => 9],
            [ 'measure_id' => 2, 'ingredient_id' => 9],
            [ 'measure_id' => 18, 'ingredient_id' => 9],
            [ 'measure_id' => 19, 'ingredient_id' => 9],

            [ 'measure_id' => 11, 'ingredient_id' => 10],
            [ 'measure_id' => 12, 'ingredient_id' => 10],
            [ 'measure_id' => 15, 'ingredient_id' => 10],
            [ 'measure_id' => 17, 'ingredient_id' => 10],

            [ 'measure_id' => 11, 'ingredient_id' => 11],
            [ 'measure_id' => 12, 'ingredient_id' => 11],
            [ 'measure_id' => 15, 'ingredient_id' => 11],
            [ 'measure_id' => 17, 'ingredient_id' => 11],

            [ 'measure_id' => 11, 'ingredient_id' => 12],
            [ 'measure_id' => 12, 'ingredient_id' => 12],
            [ 'measure_id' => 15, 'ingredient_id' => 12],

            [ 'measure_id' => 11, 'ingredient_id' => 13],
            [ 'measure_id' => 12, 'ingredient_id' => 13],
            [ 'measure_id' => 15, 'ingredient_id' => 13],
            [ 'measure_id' => 1, 'ingredient_id' => 13],
            [ 'measure_id' => 2, 'ingredient_id' => 13],
            [ 'measure_id' => 5, 'ingredient_id' => 13],

            [ 'measure_id' => 11, 'ingredient_id' => 14],
            [ 'measure_id' => 12, 'ingredient_id' => 14],
            [ 'measure_id' => 15, 'ingredient_id' => 14],
            [ 'measure_id' => 16, 'ingredient_id' => 14],
            [ 'measure_id' => 1, 'ingredient_id' => 14],
            [ 'measure_id' => 2, 'ingredient_id' => 14],
            [ 'measure_id' => 18, 'ingredient_id' => 14],
            [ 'measure_id' => 19, 'ingredient_id' => 14],

            [ 'measure_id' => 11, 'ingredient_id' => 15],
            [ 'measure_id' => 12, 'ingredient_id' => 15],
            [ 'measure_id' => 17, 'ingredient_id' => 15],
            [ 'measure_id' => 15, 'ingredient_id' => 15],
            [ 'measure_id' => 20, 'ingredient_id' => 15],

            [ 'measure_id' => 11, 'ingredient_id' => 16],
            [ 'measure_id' => 12, 'ingredient_id' => 16],
            [ 'measure_id' => 15, 'ingredient_id' => 16],
            [ 'measure_id' => 17, 'ingredient_id' => 16],

            [ 'measure_id' => 11, 'ingredient_id' => 17],
            [ 'measure_id' => 12, 'ingredient_id' => 17],
            [ 'measure_id' => 15, 'ingredient_id' => 17],
            [ 'measure_id' => 16, 'ingredient_id' => 17],
            [ 'measure_id' => 1, 'ingredient_id' => 17],
            [ 'measure_id' => 2, 'ingredient_id' => 17],
            [ 'measure_id' => 18, 'ingredient_id' => 17],
            [ 'measure_id' => 19, 'ingredient_id' => 17],
            [ 'measure_id' => 22, 'ingredient_id' => 17],

            [ 'measure_id' => 11, 'ingredient_id' => 18],
            [ 'measure_id' => 12, 'ingredient_id' => 18],
            [ 'measure_id' => 15, 'ingredient_id' => 18],
            [ 'measure_id' => 16, 'ingredient_id' => 18],
            [ 'measure_id' => 1, 'ingredient_id' => 18],
            [ 'measure_id' => 2, 'ingredient_id' => 18],
            [ 'measure_id' => 18, 'ingredient_id' => 18],
            [ 'measure_id' => 19, 'ingredient_id' => 18],

            [ 'measure_id' => 11, 'ingredient_id' => 19],
            [ 'measure_id' => 12, 'ingredient_id' => 19],
            [ 'measure_id' => 15, 'ingredient_id' => 19],
            [ 'measure_id' => 1, 'ingredient_id' => 19],
            [ 'measure_id' => 2, 'ingredient_id' => 19],
            [ 'measure_id' => 13, 'ingredient_id' => 19],
            [ 'measure_id' => 14, 'ingredient_id' => 19],

            [ 'measure_id' => 11, 'ingredient_id' => 20],
            [ 'measure_id' => 12, 'ingredient_id' => 20],
            [ 'measure_id' => 15, 'ingredient_id' => 20],
            [ 'measure_id' => 1, 'ingredient_id' => 20],
            [ 'measure_id' => 2, 'ingredient_id' => 20],
            [ 'measure_id' => 13, 'ingredient_id' => 20],
            [ 'measure_id' => 14, 'ingredient_id' => 20],

            [ 'measure_id' => 11, 'ingredient_id' => 21],
            [ 'measure_id' => 12, 'ingredient_id' => 21],
            [ 'measure_id' => 15, 'ingredient_id' => 21],
            [ 'measure_id' => 16, 'ingredient_id' => 21],
            [ 'measure_id' => 1, 'ingredient_id' => 21],
            [ 'measure_id' => 2, 'ingredient_id' => 21],
            [ 'measure_id' => 18, 'ingredient_id' => 21],
            [ 'measure_id' => 19, 'ingredient_id' => 21],

            [ 'measure_id' => 11, 'ingredient_id' => 22],
            [ 'measure_id' => 12, 'ingredient_id' => 22],
            [ 'measure_id' => 15, 'ingredient_id' => 22],
            [ 'measure_id' => 20, 'ingredient_id' => 22],

            [ 'measure_id' => 15, 'ingredient_id' => 23],
            [ 'measure_id' => 17, 'ingredient_id' => 23],

            [ 'measure_id' => 11, 'ingredient_id' => 24],
            [ 'measure_id' => 12, 'ingredient_id' => 24],
            [ 'measure_id' => 15, 'ingredient_id' => 24],
            [ 'measure_id' => 16, 'ingredient_id' => 24],
            [ 'measure_id' => 1, 'ingredient_id' => 24],
            [ 'measure_id' => 2, 'ingredient_id' => 24],
            [ 'measure_id' => 18, 'ingredient_id' => 24],
            [ 'measure_id' => 19, 'ingredient_id' => 24],

            [ 'measure_id' => 11, 'ingredient_id' => 25],
            [ 'measure_id' => 12, 'ingredient_id' => 25],
            [ 'measure_id' => 15, 'ingredient_id' => 25],
            [ 'measure_id' => 16, 'ingredient_id' => 25],
            [ 'measure_id' => 1, 'ingredient_id' => 25],
            [ 'measure_id' => 2, 'ingredient_id' => 25],
            [ 'measure_id' => 18, 'ingredient_id' => 25],
            [ 'measure_id' => 19, 'ingredient_id' => 25],

            [ 'measure_id' => 11, 'ingredient_id' => 26],
            [ 'measure_id' => 12, 'ingredient_id' => 26],
            [ 'measure_id' => 15, 'ingredient_id' => 26],
            [ 'measure_id' => 17, 'ingredient_id' => 26],

            [ 'measure_id' => 11, 'ingredient_id' => 27],
            [ 'measure_id' => 12, 'ingredient_id' => 27],
            [ 'measure_id' => 15, 'ingredient_id' => 27],
            [ 'measure_id' => 1, 'ingredient_id' => 27],
            [ 'measure_id' => 2, 'ingredient_id' => 27],
            [ 'measure_id' => 13, 'ingredient_id' => 27],
            [ 'measure_id' => 14, 'ingredient_id' => 27],

            [ 'measure_id' => 11, 'ingredient_id' => 28],
            [ 'measure_id' => 12, 'ingredient_id' => 28],
            [ 'measure_id' => 17, 'ingredient_id' => 28],
            [ 'measure_id' => 15, 'ingredient_id' => 28],
            [ 'measure_id' => 20, 'ingredient_id' => 28],

            [ 'measure_id' => 11, 'ingredient_id' => 29],
            [ 'measure_id' => 12, 'ingredient_id' => 29],
            [ 'measure_id' => 17, 'ingredient_id' => 29],
            [ 'measure_id' => 15, 'ingredient_id' => 29],
            [ 'measure_id' => 22, 'ingredient_id' => 29],

            [ 'measure_id' => 11, 'ingredient_id' => 30],
            [ 'measure_id' => 12, 'ingredient_id' => 30],
            [ 'measure_id' => 17, 'ingredient_id' => 30],
            [ 'measure_id' => 15, 'ingredient_id' => 30],
            [ 'measure_id' => 22, 'ingredient_id' => 30],

            [ 'measure_id' => 11, 'ingredient_id' => 31],
            [ 'measure_id' => 12, 'ingredient_id' => 31],
            [ 'measure_id' => 17, 'ingredient_id' => 31],
            [ 'measure_id' => 15, 'ingredient_id' => 31],
            [ 'measure_id' => 1, 'ingredient_id' => 31],
            [ 'measure_id' => 2, 'ingredient_id' => 31],
            [ 'measure_id' => 13, 'ingredient_id' => 31],
            [ 'measure_id' => 14, 'ingredient_id' => 31],

            [ 'measure_id' => 11, 'ingredient_id' => 32],
            [ 'measure_id' => 12, 'ingredient_id' => 32],
            [ 'measure_id' => 17, 'ingredient_id' => 32],
            [ 'measure_id' => 15, 'ingredient_id' => 32],

            [ 'measure_id' => 11, 'ingredient_id' => 33],
            [ 'measure_id' => 12, 'ingredient_id' => 33],
            [ 'measure_id' => 15, 'ingredient_id' => 33],
            [ 'measure_id' => 1, 'ingredient_id' => 33],
            [ 'measure_id' => 2, 'ingredient_id' => 33],
            [ 'measure_id' => 13, 'ingredient_id' => 33],
            [ 'measure_id' => 14, 'ingredient_id' => 33],

            [ 'measure_id' => 11, 'ingredient_id' => 34],
            [ 'measure_id' => 12, 'ingredient_id' => 34],
            [ 'measure_id' => 15, 'ingredient_id' => 34],
            [ 'measure_id' => 16, 'ingredient_id' => 34],
            [ 'measure_id' => 1, 'ingredient_id' => 34],
            [ 'measure_id' => 2, 'ingredient_id' => 34],
            [ 'measure_id' => 18, 'ingredient_id' => 34],
            [ 'measure_id' => 19, 'ingredient_id' => 34],

            [ 'measure_id' => 11, 'ingredient_id' => 35],
            [ 'measure_id' => 12, 'ingredient_id' => 35],
            [ 'measure_id' => 15, 'ingredient_id' => 35],
            [ 'measure_id' => 1, 'ingredient_id' => 35],
            [ 'measure_id' => 2, 'ingredient_id' => 35],

            [ 'measure_id' => 11, 'ingredient_id' => 36],
            [ 'measure_id' => 12, 'ingredient_id' => 36],
            [ 'measure_id' => 15, 'ingredient_id' => 36],
            [ 'measure_id' => 1, 'ingredient_id' => 36],
            [ 'measure_id' => 2, 'ingredient_id' => 36],
            [ 'measure_id' => 17, 'ingredient_id' => 36],

            [ 'measure_id' => 11, 'ingredient_id' => 37],
            [ 'measure_id' => 12, 'ingredient_id' => 37],
            [ 'measure_id' => 17, 'ingredient_id' => 37],
            [ 'measure_id' => 15, 'ingredient_id' => 37],
            [ 'measure_id' => 20, 'ingredient_id' => 37],

            [ 'measure_id' => 11, 'ingredient_id' => 38],
            [ 'measure_id' => 12, 'ingredient_id' => 38],
            [ 'measure_id' => 17, 'ingredient_id' => 38],
            [ 'measure_id' => 15, 'ingredient_id' => 38],

            [ 'measure_id' => 11, 'ingredient_id' => 39],
            [ 'measure_id' => 12, 'ingredient_id' => 39],
            [ 'measure_id' => 17, 'ingredient_id' => 39],
            [ 'measure_id' => 15, 'ingredient_id' => 39],

            [ 'measure_id' => 11, 'ingredient_id' => 40],
            [ 'measure_id' => 12, 'ingredient_id' => 40],
            [ 'measure_id' => 17, 'ingredient_id' => 40],
            [ 'measure_id' => 15, 'ingredient_id' => 40],

            [ 'measure_id' => 11, 'ingredient_id' => 41],
            [ 'measure_id' => 12, 'ingredient_id' => 41],
            [ 'measure_id' => 17, 'ingredient_id' => 41],
            [ 'measure_id' => 15, 'ingredient_id' => 41],
            [ 'measure_id' => 22, 'ingredient_id' => 41],

            [ 'measure_id' => 11, 'ingredient_id' => 42],
            [ 'measure_id' => 12, 'ingredient_id' => 42],
            [ 'measure_id' => 15, 'ingredient_id' => 42],
            [ 'measure_id' => 16, 'ingredient_id' => 42],
            [ 'measure_id' => 1, 'ingredient_id' => 42],
            [ 'measure_id' => 2, 'ingredient_id' => 42],
            [ 'measure_id' => 18, 'ingredient_id' => 42],
            [ 'measure_id' => 19, 'ingredient_id' => 42],

            [ 'measure_id' => 11, 'ingredient_id' => 43],
            [ 'measure_id' => 12, 'ingredient_id' => 43],
            [ 'measure_id' => 15, 'ingredient_id' => 43],

            [ 'measure_id' => 11, 'ingredient_id' => 44],
            [ 'measure_id' => 12, 'ingredient_id' => 44],
            [ 'measure_id' => 15, 'ingredient_id' => 44],
            [ 'measure_id' => 1, 'ingredient_id' => 44],
            [ 'measure_id' => 2, 'ingredient_id' => 44],
            [ 'measure_id' => 13, 'ingredient_id' => 44],
            [ 'measure_id' => 14, 'ingredient_id' => 44],

            [ 'measure_id' => 11, 'ingredient_id' => 45],
            [ 'measure_id' => 12, 'ingredient_id' => 45],
            [ 'measure_id' => 15, 'ingredient_id' => 45],
            [ 'measure_id' => 1, 'ingredient_id' => 45],
            [ 'measure_id' => 2, 'ingredient_id' => 45],
            [ 'measure_id' => 13, 'ingredient_id' => 45],
            [ 'measure_id' => 14, 'ingredient_id' => 45],

            [ 'measure_id' => 11, 'ingredient_id' => 46],
            [ 'measure_id' => 12, 'ingredient_id' => 46],
            [ 'measure_id' => 15, 'ingredient_id' => 46],
            [ 'measure_id' => 16, 'ingredient_id' => 46],
            [ 'measure_id' => 1, 'ingredient_id' => 46],
            [ 'measure_id' => 2, 'ingredient_id' => 46],
            [ 'measure_id' => 18, 'ingredient_id' => 46],
            [ 'measure_id' => 19, 'ingredient_id' => 46],

            [ 'measure_id' => 11, 'ingredient_id' => 47],
            [ 'measure_id' => 12, 'ingredient_id' => 47],
            [ 'measure_id' => 15, 'ingredient_id' => 47],
            [ 'measure_id' => 16, 'ingredient_id' => 47],
            [ 'measure_id' => 1, 'ingredient_id' => 47],
            [ 'measure_id' => 2, 'ingredient_id' => 47],
            [ 'measure_id' => 18, 'ingredient_id' => 47],
            [ 'measure_id' => 19, 'ingredient_id' => 47],

            [ 'measure_id' => 11, 'ingredient_id' => 48],
            [ 'measure_id' => 12, 'ingredient_id' => 48],
            [ 'measure_id' => 15, 'ingredient_id' => 48],
            [ 'measure_id' => 1, 'ingredient_id' => 48],
            [ 'measure_id' => 2, 'ingredient_id' => 48],
            [ 'measure_id' => 13, 'ingredient_id' => 48],
            [ 'measure_id' => 14, 'ingredient_id' => 48],

            [ 'measure_id' => 11, 'ingredient_id' => 49],
            [ 'measure_id' => 12, 'ingredient_id' => 49],
            [ 'measure_id' => 15, 'ingredient_id' => 49],
            [ 'measure_id' => 1, 'ingredient_id' => 49],
            [ 'measure_id' => 2, 'ingredient_id' => 49],

            [ 'measure_id' => 17, 'ingredient_id' => 50],
            [ 'measure_id' => 15, 'ingredient_id' => 50],
            [ 'measure_id' => 18, 'ingredient_id' => 50],
            [ 'measure_id' => 5, 'ingredient_id' => 50],

            [ 'measure_id' => 11, 'ingredient_id' => 51],
            [ 'measure_id' => 12, 'ingredient_id' => 51],
            [ 'measure_id' => 15, 'ingredient_id' => 51],
            [ 'measure_id' => 16, 'ingredient_id' => 51],
            [ 'measure_id' => 1, 'ingredient_id' => 51],
            [ 'measure_id' => 2, 'ingredient_id' => 51],
            [ 'measure_id' => 18, 'ingredient_id' => 51],
            [ 'measure_id' => 19, 'ingredient_id' => 51],
            [ 'measure_id' => 5, 'ingredient_id' => 51],

            [ 'measure_id' => 11, 'ingredient_id' => 52],
            [ 'measure_id' => 12, 'ingredient_id' => 52],
            [ 'measure_id' => 17, 'ingredient_id' => 52],
            [ 'measure_id' => 15, 'ingredient_id' => 52],
            [ 'measure_id' => 22, 'ingredient_id' => 52],

            [ 'measure_id' => 11, 'ingredient_id' => 53],
            [ 'measure_id' => 12, 'ingredient_id' => 53],
            [ 'measure_id' => 15, 'ingredient_id' => 53],

            [ 'measure_id' => 11, 'ingredient_id' => 54],
            [ 'measure_id' => 12, 'ingredient_id' => 54],
            [ 'measure_id' => 15, 'ingredient_id' => 54],
            [ 'measure_id' => 1, 'ingredient_id' => 54],
            [ 'measure_id' => 2, 'ingredient_id' => 54],

            [ 'measure_id' => 11, 'ingredient_id' => 55],
            [ 'measure_id' => 12, 'ingredient_id' => 55],
            [ 'measure_id' => 15, 'ingredient_id' => 55],
            [ 'measure_id' => 1, 'ingredient_id' => 55],
            [ 'measure_id' => 2, 'ingredient_id' => 55],

            [ 'measure_id' => 11, 'ingredient_id' => 56],
            [ 'measure_id' => 12, 'ingredient_id' => 56],
            [ 'measure_id' => 17, 'ingredient_id' => 56],
            [ 'measure_id' => 15, 'ingredient_id' => 56],

            [ 'measure_id' => 11, 'ingredient_id' => 57],
            [ 'measure_id' => 12, 'ingredient_id' => 57],
            [ 'measure_id' => 15, 'ingredient_id' => 57],
            [ 'measure_id' => 1, 'ingredient_id' => 57],
            [ 'measure_id' => 2, 'ingredient_id' => 57],

            [ 'measure_id' => 11, 'ingredient_id' => 58],
            [ 'measure_id' => 12, 'ingredient_id' => 58],
            [ 'measure_id' => 15, 'ingredient_id' => 58],
            [ 'measure_id' => 16, 'ingredient_id' => 58],
            [ 'measure_id' => 1, 'ingredient_id' => 58],
            [ 'measure_id' => 2, 'ingredient_id' => 58],
            [ 'measure_id' => 18, 'ingredient_id' => 58],
            [ 'measure_id' => 19, 'ingredient_id' => 58],

            [ 'measure_id' => 11, 'ingredient_id' => 59],
            [ 'measure_id' => 12, 'ingredient_id' => 59],
            [ 'measure_id' => 17, 'ingredient_id' => 59],
            [ 'measure_id' => 15, 'ingredient_id' => 59],

            [ 'measure_id' => 11, 'ingredient_id' => 60],
            [ 'measure_id' => 12, 'ingredient_id' => 60],
            [ 'measure_id' => 17, 'ingredient_id' => 60],
            [ 'measure_id' => 15, 'ingredient_id' => 60],

            [ 'measure_id' => 11, 'ingredient_id' => 61],
            [ 'measure_id' => 12, 'ingredient_id' => 61],
            [ 'measure_id' => 15, 'ingredient_id' => 61],
            [ 'measure_id' => 1, 'ingredient_id' => 61],

            [ 'measure_id' => 11, 'ingredient_id' => 62],
            [ 'measure_id' => 12, 'ingredient_id' => 62],
            [ 'measure_id' => 17, 'ingredient_id' => 62],
            [ 'measure_id' => 15, 'ingredient_id' => 62],
            [ 'measure_id' => 22, 'ingredient_id' => 62],

            [ 'measure_id' => 17, 'ingredient_id' => 63],
            [ 'measure_id' => 15, 'ingredient_id' => 63],

            [ 'measure_id' => 11, 'ingredient_id' => 64],
            [ 'measure_id' => 12, 'ingredient_id' => 64],
            [ 'measure_id' => 15, 'ingredient_id' => 64],
            [ 'measure_id' => 1, 'ingredient_id' => 64],
            [ 'measure_id' => 2, 'ingredient_id' => 64],
            [ 'measure_id' => 17, 'ingredient_id' => 64],

            [ 'measure_id' => 11, 'ingredient_id' => 66],
            [ 'measure_id' => 12, 'ingredient_id' => 66],
            [ 'measure_id' => 17, 'ingredient_id' => 66],
            [ 'measure_id' => 15, 'ingredient_id' => 66],

            [ 'measure_id' => 11, 'ingredient_id' => 67],
            [ 'measure_id' => 12, 'ingredient_id' => 67],
            [ 'measure_id' => 15, 'ingredient_id' => 67],

            [ 'measure_id' => 11, 'ingredient_id' => 69],
            [ 'measure_id' => 12, 'ingredient_id' => 69],
            [ 'measure_id' => 15, 'ingredient_id' => 69],
            [ 'measure_id' => 16, 'ingredient_id' => 69],
            [ 'measure_id' => 1, 'ingredient_id' => 69],
            [ 'measure_id' => 2, 'ingredient_id' => 69],
            [ 'measure_id' => 18, 'ingredient_id' => 69],
            [ 'measure_id' => 19, 'ingredient_id' => 69],

            [ 'measure_id' => 11, 'ingredient_id' => 70],
            [ 'measure_id' => 12, 'ingredient_id' => 70],
            [ 'measure_id' => 15, 'ingredient_id' => 70],
            [ 'measure_id' => 5, 'ingredient_id' => 70],
            [ 'measure_id' => 1, 'ingredient_id' => 70],

            [ 'measure_id' => 15, 'ingredient_id' => 71],
            [ 'measure_id' => 13, 'ingredient_id' => 71],
            [ 'measure_id' => 14, 'ingredient_id' => 71],

            [ 'measure_id' => 11, 'ingredient_id' => 73],
            [ 'measure_id' => 12, 'ingredient_id' => 73],
            [ 'measure_id' => 17, 'ingredient_id' => 73],
            [ 'measure_id' => 15, 'ingredient_id' => 73],
            [ 'measure_id' => 20, 'ingredient_id' => 73],

            [ 'measure_id' => 11, 'ingredient_id' => 75],
            [ 'measure_id' => 12, 'ingredient_id' => 75],
            [ 'measure_id' => 17, 'ingredient_id' => 75],
            [ 'measure_id' => 15, 'ingredient_id' => 75],

            [ 'measure_id' => 11, 'ingredient_id' => 76],
            [ 'measure_id' => 12, 'ingredient_id' => 76],
            [ 'measure_id' => 15, 'ingredient_id' => 76],

            [ 'measure_id' => 11, 'ingredient_id' => 77],
            [ 'measure_id' => 12, 'ingredient_id' => 77],
            [ 'measure_id' => 15, 'ingredient_id' => 77],
            [ 'measure_id' => 16, 'ingredient_id' => 77],
            [ 'measure_id' => 1, 'ingredient_id' => 77],
            [ 'measure_id' => 2, 'ingredient_id' => 77],
            [ 'measure_id' => 18, 'ingredient_id' => 77],
            [ 'measure_id' => 19, 'ingredient_id' => 77],

            [ 'measure_id' => 11, 'ingredient_id' => 78],
            [ 'measure_id' => 12, 'ingredient_id' => 78],
            [ 'measure_id' => 17, 'ingredient_id' => 78],
            [ 'measure_id' => 15, 'ingredient_id' => 78],

            [ 'measure_id' => 11, 'ingredient_id' => 79],
            [ 'measure_id' => 12, 'ingredient_id' => 79],
            [ 'measure_id' => 15, 'ingredient_id' => 79],
            [ 'measure_id' => 16, 'ingredient_id' => 79],
            [ 'measure_id' => 1, 'ingredient_id' => 79],
            [ 'measure_id' => 2, 'ingredient_id' => 79],
            [ 'measure_id' => 18, 'ingredient_id' => 79],
            [ 'measure_id' => 19, 'ingredient_id' => 79],

            [ 'measure_id' => 17, 'ingredient_id' => 80],
            [ 'measure_id' => 15, 'ingredient_id' => 80],

            [ 'measure_id' => 11, 'ingredient_id' => 81],
            [ 'measure_id' => 12, 'ingredient_id' => 81],
            [ 'measure_id' => 15, 'ingredient_id' => 81],

            [ 'measure_id' => 11, 'ingredient_id' => 82],
            [ 'measure_id' => 12, 'ingredient_id' => 82],
            [ 'measure_id' => 15, 'ingredient_id' => 82],

            [ 'measure_id' => 11, 'ingredient_id' => 83],
            [ 'measure_id' => 12, 'ingredient_id' => 83],
            [ 'measure_id' => 15, 'ingredient_id' => 83],

            [ 'measure_id' => 11, 'ingredient_id' => 84],
            [ 'measure_id' => 12, 'ingredient_id' => 84],
            [ 'measure_id' => 15, 'ingredient_id' => 84],
            [ 'measure_id' => 5, 'ingredient_id' => 84],
            [ 'measure_id' => 1, 'ingredient_id' => 84],

            [ 'measure_id' => 13, 'ingredient_id' => 85],
            [ 'measure_id' => 14, 'ingredient_id' => 85],
            [ 'measure_id' => 15, 'ingredient_id' => 85],

            [ 'measure_id' => 11, 'ingredient_id' => 86],
            [ 'measure_id' => 12, 'ingredient_id' => 86],
            [ 'measure_id' => 15, 'ingredient_id' => 86],
            [ 'measure_id' => 17, 'ingredient_id' => 86],

            [ 'measure_id' => 13, 'ingredient_id' => 87],
            [ 'measure_id' => 14, 'ingredient_id' => 87],
            [ 'measure_id' => 15, 'ingredient_id' => 87],
            [ 'measure_id' => 1, 'ingredient_id' => 87],

            [ 'measure_id' => 11, 'ingredient_id' => 88],
            [ 'measure_id' => 12, 'ingredient_id' => 88],
            [ 'measure_id' => 15, 'ingredient_id' => 88],
            [ 'measure_id' => 16, 'ingredient_id' => 88],
            [ 'measure_id' => 1, 'ingredient_id' => 88],
            [ 'measure_id' => 2, 'ingredient_id' => 88],
            [ 'measure_id' => 18, 'ingredient_id' => 88],
            [ 'measure_id' => 19, 'ingredient_id' => 88],

            [ 'measure_id' => 11, 'ingredient_id' => 89],
            [ 'measure_id' => 12, 'ingredient_id' => 89],
            [ 'measure_id' => 17, 'ingredient_id' => 89],
            [ 'measure_id' => 15, 'ingredient_id' => 89],

            [ 'measure_id' => 11, 'ingredient_id' => 90],
            [ 'measure_id' => 12, 'ingredient_id' => 90],
            [ 'measure_id' => 17, 'ingredient_id' => 90],
            [ 'measure_id' => 15, 'ingredient_id' => 90],

            [ 'measure_id' => 13, 'ingredient_id' => 91],
            [ 'measure_id' => 14, 'ingredient_id' => 91],
            [ 'measure_id' => 15, 'ingredient_id' => 91],
            [ 'measure_id' => 1, 'ingredient_id' => 91],

            [ 'measure_id' => 11, 'ingredient_id' => 92],
            [ 'measure_id' => 12, 'ingredient_id' => 92],
            [ 'measure_id' => 15, 'ingredient_id' => 92],
            [ 'measure_id' => 1, 'ingredient_id' => 92],
            [ 'measure_id' => 2, 'ingredient_id' => 92],
            [ 'measure_id' => 13, 'ingredient_id' => 92],
            [ 'measure_id' => 14, 'ingredient_id' => 92],

            [ 'measure_id' => 11, 'ingredient_id' => 93],
            [ 'measure_id' => 12, 'ingredient_id' => 93],
            [ 'measure_id' => 15, 'ingredient_id' => 93],

            [ 'measure_id' => 11, 'ingredient_id' => 94],
            [ 'measure_id' => 12, 'ingredient_id' => 94],
            [ 'measure_id' => 15, 'ingredient_id' => 94],
            [ 'measure_id' => 17, 'ingredient_id' => 94],

            [ 'measure_id' => 11, 'ingredient_id' => 95],
            [ 'measure_id' => 12, 'ingredient_id' => 95],
            [ 'measure_id' => 17, 'ingredient_id' => 95],
            [ 'measure_id' => 15, 'ingredient_id' => 95],

            [ 'measure_id' => 11, 'ingredient_id' => 96],
            [ 'measure_id' => 12, 'ingredient_id' => 96],
            [ 'measure_id' => 15, 'ingredient_id' => 96],
            [ 'measure_id' => 16, 'ingredient_id' => 96],
            [ 'measure_id' => 1, 'ingredient_id' => 96],
            [ 'measure_id' => 2, 'ingredient_id' => 96],
            [ 'measure_id' => 18, 'ingredient_id' => 96],
            [ 'measure_id' => 19, 'ingredient_id' => 96],

            [ 'measure_id' => 11, 'ingredient_id' => 97],
            [ 'measure_id' => 12, 'ingredient_id' => 97],
            [ 'measure_id' => 15, 'ingredient_id' => 97],
            [ 'measure_id' => 1, 'ingredient_id' => 97],
            [ 'measure_id' => 2, 'ingredient_id' => 97],
            [ 'measure_id' => 13, 'ingredient_id' => 97],
            [ 'measure_id' => 14, 'ingredient_id' => 97],

            [ 'measure_id' => 11, 'ingredient_id' => 98],
            [ 'measure_id' => 12, 'ingredient_id' => 98],
            [ 'measure_id' => 15, 'ingredient_id' => 98],
            [ 'measure_id' => 20, 'ingredient_id' => 98],

            [ 'measure_id' => 11, 'ingredient_id' => 99],
            [ 'measure_id' => 12, 'ingredient_id' => 99],
            [ 'measure_id' => 15, 'ingredient_id' => 99],

            [ 'measure_id' => 11, 'ingredient_id' => 100],
            [ 'measure_id' => 12, 'ingredient_id' => 100],
            [ 'measure_id' => 15, 'ingredient_id' => 100],
            [ 'measure_id' => 1, 'ingredient_id' => 100],
            [ 'measure_id' => 17, 'ingredient_id' => 100],

            [ 'measure_id' => 11, 'ingredient_id' => 101],
            [ 'measure_id' => 12, 'ingredient_id' => 101],
            [ 'measure_id' => 15, 'ingredient_id' => 101],

            [ 'measure_id' => 15, 'ingredient_id' => 102],
            [ 'measure_id' => 13, 'ingredient_id' => 102],
            [ 'measure_id' => 14, 'ingredient_id' => 102],

            [ 'measure_id' => 13, 'ingredient_id' => 103],
            [ 'measure_id' => 14, 'ingredient_id' => 103],
            [ 'measure_id' => 15, 'ingredient_id' => 103],

            [ 'measure_id' => 11, 'ingredient_id' => 104],
            [ 'measure_id' => 12, 'ingredient_id' => 104],
            [ 'measure_id' => 15, 'ingredient_id' => 104],

            [ 'measure_id' => 11, 'ingredient_id' => 105],
            [ 'measure_id' => 12, 'ingredient_id' => 105],
            [ 'measure_id' => 15, 'ingredient_id' => 105],

            [ 'measure_id' => 11, 'ingredient_id' => 106],
            [ 'measure_id' => 12, 'ingredient_id' => 106],
            [ 'measure_id' => 15, 'ingredient_id' => 106],
            [ 'measure_id' => 1, 'ingredient_id' => 106],
            [ 'measure_id' => 2, 'ingredient_id' => 106],

            [ 'measure_id' => 11, 'ingredient_id' => 107],
            [ 'measure_id' => 12, 'ingredient_id' => 107],
            [ 'measure_id' => 15, 'ingredient_id' => 107],
            [ 'measure_id' => 1, 'ingredient_id' => 107],

            [ 'measure_id' => 11, 'ingredient_id' => 108],
            [ 'measure_id' => 12, 'ingredient_id' => 108],
            [ 'measure_id' => 15, 'ingredient_id' => 108],
            [ 'measure_id' => 17, 'ingredient_id' => 108],

            [ 'measure_id' => 11, 'ingredient_id' => 109],
            [ 'measure_id' => 12, 'ingredient_id' => 109],
            [ 'measure_id' => 15, 'ingredient_id' => 109],

            [ 'measure_id' => 11, 'ingredient_id' => 110],
            [ 'measure_id' => 12, 'ingredient_id' => 110],
            [ 'measure_id' => 17, 'ingredient_id' => 110],
            [ 'measure_id' => 15, 'ingredient_id' => 110],
            [ 'measure_id' => 20, 'ingredient_id' => 110],

            [ 'measure_id' => 11, 'ingredient_id' => 112],
            [ 'measure_id' => 12, 'ingredient_id' => 112],
            [ 'measure_id' => 17, 'ingredient_id' => 112],
            [ 'measure_id' => 15, 'ingredient_id' => 112],
            [ 'measure_id' => 20, 'ingredient_id' => 112],

            [ 'measure_id' => 11, 'ingredient_id' => 113],
            [ 'measure_id' => 12, 'ingredient_id' => 113],
            [ 'measure_id' => 15, 'ingredient_id' => 113],

            [ 'measure_id' => 11, 'ingredient_id' => 114],
            [ 'measure_id' => 12, 'ingredient_id' => 114],
            [ 'measure_id' => 15, 'ingredient_id' => 114],
            [ 'measure_id' => 1, 'ingredient_id' => 114],
            [ 'measure_id' => 2, 'ingredient_id' => 114],
            [ 'measure_id' => 13, 'ingredient_id' => 114],
            [ 'measure_id' => 14, 'ingredient_id' => 114],

            [ 'measure_id' => 11, 'ingredient_id' => 115],
            [ 'measure_id' => 12, 'ingredient_id' => 115],
            [ 'measure_id' => 17, 'ingredient_id' => 115],
            [ 'measure_id' => 15, 'ingredient_id' => 115],

            [ 'measure_id' => 11, 'ingredient_id' => 116],
            [ 'measure_id' => 12, 'ingredient_id' => 116],
            [ 'measure_id' => 15, 'ingredient_id' => 116],

            [ 'measure_id' => 13, 'ingredient_id' => 117],
            [ 'measure_id' => 14, 'ingredient_id' => 117],
            [ 'measure_id' => 15, 'ingredient_id' => 117],
            [ 'measure_id' => 1, 'ingredient_id' => 117],

            [ 'measure_id' => 11, 'ingredient_id' => 118],
            [ 'measure_id' => 12, 'ingredient_id' => 118],
            [ 'measure_id' => 15, 'ingredient_id' => 118],
            [ 'measure_id' => 16, 'ingredient_id' => 118],
            [ 'measure_id' => 1, 'ingredient_id' => 118],
            [ 'measure_id' => 2, 'ingredient_id' => 118],
            [ 'measure_id' => 18, 'ingredient_id' => 118],
            [ 'measure_id' => 19, 'ingredient_id' => 118],

            [ 'measure_id' => 17, 'ingredient_id' => 119],
            [ 'measure_id' => 15, 'ingredient_id' => 119],

            [ 'measure_id' => 11, 'ingredient_id' => 120],
            [ 'measure_id' => 12, 'ingredient_id' => 120],
            [ 'measure_id' => 15, 'ingredient_id' => 120],
            [ 'measure_id' => 16, 'ingredient_id' => 120],
            [ 'measure_id' => 1, 'ingredient_id' => 120],
            [ 'measure_id' => 2, 'ingredient_id' => 120],
            [ 'measure_id' => 18, 'ingredient_id' => 120],
            [ 'measure_id' => 19, 'ingredient_id' => 120],

            [ 'measure_id' => 11, 'ingredient_id' => 121],
            [ 'measure_id' => 12, 'ingredient_id' => 121],
            [ 'measure_id' => 15, 'ingredient_id' => 121],
            [ 'measure_id' => 16, 'ingredient_id' => 121],
            [ 'measure_id' => 1, 'ingredient_id' => 121],
            [ 'measure_id' => 2, 'ingredient_id' => 121],
            [ 'measure_id' => 18, 'ingredient_id' => 121],
            [ 'measure_id' => 19, 'ingredient_id' => 121],

            [ 'measure_id' => 11, 'ingredient_id' => 122],
            [ 'measure_id' => 12, 'ingredient_id' => 122],
            [ 'measure_id' => 15, 'ingredient_id' => 122],
            [ 'measure_id' => 17, 'ingredient_id' => 122],

            [ 'measure_id' => 11, 'ingredient_id' => 123],
            [ 'measure_id' => 12, 'ingredient_id' => 123],
            [ 'measure_id' => 15, 'ingredient_id' => 123],

            [ 'measure_id' => 11, 'ingredient_id' => 124],
            [ 'measure_id' => 12, 'ingredient_id' => 124],
            [ 'measure_id' => 15, 'ingredient_id' => 124],

            [ 'measure_id' => 11, 'ingredient_id' => 125],
            [ 'measure_id' => 12, 'ingredient_id' => 125],
            [ 'measure_id' => 15, 'ingredient_id' => 125],
            [ 'measure_id' => 1, 'ingredient_id' => 125],
            [ 'measure_id' => 2, 'ingredient_id' => 125],
            [ 'measure_id' => 13, 'ingredient_id' => 125],
            [ 'measure_id' => 14, 'ingredient_id' => 125],

            [ 'measure_id' => 11, 'ingredient_id' => 126],
            [ 'measure_id' => 12, 'ingredient_id' => 126],
            [ 'measure_id' => 15, 'ingredient_id' => 126],

            [ 'measure_id' => 11, 'ingredient_id' => 127],
            [ 'measure_id' => 12, 'ingredient_id' => 127],
            [ 'measure_id' => 17, 'ingredient_id' => 127],
            [ 'measure_id' => 15, 'ingredient_id' => 127],

            [ 'measure_id' => 11, 'ingredient_id' => 128],
            [ 'measure_id' => 12, 'ingredient_id' => 128],
            [ 'measure_id' => 15, 'ingredient_id' => 128],
            [ 'measure_id' => 1, 'ingredient_id' => 128],
            [ 'measure_id' => 2, 'ingredient_id' => 128],

            [ 'measure_id' => 11, 'ingredient_id' => 129],
            [ 'measure_id' => 12, 'ingredient_id' => 129],
            [ 'measure_id' => 15, 'ingredient_id' => 129],
            [ 'measure_id' => 1, 'ingredient_id' => 129],
            [ 'measure_id' => 2, 'ingredient_id' => 129],

            [ 'measure_id' => 11, 'ingredient_id' => 130],
            [ 'measure_id' => 12, 'ingredient_id' => 130],
            [ 'measure_id' => 15, 'ingredient_id' => 130],

            [ 'measure_id' => 11, 'ingredient_id' => 131],
            [ 'measure_id' => 12, 'ingredient_id' => 131],
            [ 'measure_id' => 15, 'ingredient_id' => 131],

            [ 'measure_id' => 11, 'ingredient_id' => 132],
            [ 'measure_id' => 12, 'ingredient_id' => 132],
            [ 'measure_id' => 15, 'ingredient_id' => 132],
            [ 'measure_id' => 17, 'ingredient_id' => 132],

            [ 'measure_id' => 11, 'ingredient_id' => 133],
            [ 'measure_id' => 12, 'ingredient_id' => 133],
            [ 'measure_id' => 15, 'ingredient_id' => 133],
            [ 'measure_id' => 17, 'ingredient_id' => 133],

            [ 'measure_id' => 11, 'ingredient_id' => 134],
            [ 'measure_id' => 12, 'ingredient_id' => 134],
            [ 'measure_id' => 15, 'ingredient_id' => 134],

            [ 'measure_id' => 11, 'ingredient_id' => 135],
            [ 'measure_id' => 12, 'ingredient_id' => 135],
            [ 'measure_id' => 15, 'ingredient_id' => 135],

            [ 'measure_id' => 11, 'ingredient_id' => 136],
            [ 'measure_id' => 12, 'ingredient_id' => 136],
            [ 'measure_id' => 15, 'ingredient_id' => 136],
            [ 'measure_id' => 5, 'ingredient_id' => 136],

            [ 'measure_id' => 11, 'ingredient_id' => 137],
            [ 'measure_id' => 12, 'ingredient_id' => 137],
            [ 'measure_id' => 15, 'ingredient_id' => 137],
            [ 'measure_id' => 1, 'ingredient_id' => 137],
            [ 'measure_id' => 2, 'ingredient_id' => 137],

            [ 'measure_id' => 11, 'ingredient_id' => 138],
            [ 'measure_id' => 12, 'ingredient_id' => 138],
            [ 'measure_id' => 15, 'ingredient_id' => 138],
            [ 'measure_id' => 1, 'ingredient_id' => 138],
            [ 'measure_id' => 2, 'ingredient_id' => 138],
            [ 'measure_id' => 13, 'ingredient_id' => 138],
            [ 'measure_id' => 14, 'ingredient_id' => 138],

            [ 'measure_id' => 11, 'ingredient_id' => 139],
            [ 'measure_id' => 12, 'ingredient_id' => 139],
            [ 'measure_id' => 17, 'ingredient_id' => 139],
            [ 'measure_id' => 15, 'ingredient_id' => 139],

            [ 'measure_id' => 11, 'ingredient_id' => 140],
            [ 'measure_id' => 12, 'ingredient_id' => 140],
            [ 'measure_id' => 15, 'ingredient_id' => 140],
            [ 'measure_id' => 16, 'ingredient_id' => 140],
            [ 'measure_id' => 1, 'ingredient_id' => 140],
            [ 'measure_id' => 2, 'ingredient_id' => 140],
            [ 'measure_id' => 18, 'ingredient_id' => 140],
            [ 'measure_id' => 19, 'ingredient_id' => 140],
            [ 'measure_id' => 5, 'ingredient_id' => 140],

            [ 'measure_id' => 11, 'ingredient_id' => 141],
            [ 'measure_id' => 12, 'ingredient_id' => 141],
            [ 'measure_id' => 15, 'ingredient_id' => 141],
            [ 'measure_id' => 16, 'ingredient_id' => 141],
            [ 'measure_id' => 1, 'ingredient_id' => 141],
            [ 'measure_id' => 2, 'ingredient_id' => 141],
            [ 'measure_id' => 18, 'ingredient_id' => 141],
            [ 'measure_id' => 19, 'ingredient_id' => 141],
            [ 'measure_id' => 5, 'ingredient_id' => 141],

            [ 'measure_id' => 11, 'ingredient_id' => 142],
            [ 'measure_id' => 12, 'ingredient_id' => 142],
            [ 'measure_id' => 15, 'ingredient_id' => 142],
            [ 'measure_id' => 16, 'ingredient_id' => 142],
            [ 'measure_id' => 1, 'ingredient_id' => 142],
            [ 'measure_id' => 2, 'ingredient_id' => 142],
            [ 'measure_id' => 18, 'ingredient_id' => 142],
            [ 'measure_id' => 19, 'ingredient_id' => 142],
            [ 'measure_id' => 5, 'ingredient_id' => 142],

            [ 'measure_id' => 11, 'ingredient_id' => 143],
            [ 'measure_id' => 12, 'ingredient_id' => 143],
            [ 'measure_id' => 15, 'ingredient_id' => 143],
            [ 'measure_id' => 16, 'ingredient_id' => 143],
            [ 'measure_id' => 1, 'ingredient_id' => 143],
            [ 'measure_id' => 2, 'ingredient_id' => 143],
            [ 'measure_id' => 18, 'ingredient_id' => 143],
            [ 'measure_id' => 19, 'ingredient_id' => 143],

            [ 'measure_id' => 11, 'ingredient_id' => 144],
            [ 'measure_id' => 12, 'ingredient_id' => 144],
            [ 'measure_id' => 15, 'ingredient_id' => 144],
            [ 'measure_id' => 16, 'ingredient_id' => 144],
            [ 'measure_id' => 1, 'ingredient_id' => 144],
            [ 'measure_id' => 2, 'ingredient_id' => 144],
            [ 'measure_id' => 18, 'ingredient_id' => 144],
            [ 'measure_id' => 19, 'ingredient_id' => 144],

            [ 'measure_id' => 13, 'ingredient_id' => 145],
            [ 'measure_id' => 14, 'ingredient_id' => 145],
            [ 'measure_id' => 15, 'ingredient_id' => 145],
            [ 'measure_id' => 1, 'ingredient_id' => 145],

            [ 'measure_id' => 11, 'ingredient_id' => 146],
            [ 'measure_id' => 12, 'ingredient_id' => 146],
            [ 'measure_id' => 15, 'ingredient_id' => 146],
            [ 'measure_id' => 1, 'ingredient_id' => 146],
            [ 'measure_id' => 2, 'ingredient_id' => 146],
            [ 'measure_id' => 13, 'ingredient_id' => 146],
            [ 'measure_id' => 14, 'ingredient_id' => 146],

            [ 'measure_id' => 13, 'ingredient_id' => 147],
            [ 'measure_id' => 14, 'ingredient_id' => 147],
            [ 'measure_id' => 1, 'ingredient_id' => 147],
            [ 'measure_id' => 2, 'ingredient_id' => 147],
            [ 'measure_id' => 15, 'ingredient_id' => 147],

            [ 'measure_id' => 11, 'ingredient_id' => 148],
            [ 'measure_id' => 12, 'ingredient_id' => 148],
            [ 'measure_id' => 17, 'ingredient_id' => 148],
            [ 'measure_id' => 15, 'ingredient_id' => 148],

            [ 'measure_id' => 1, 'ingredient_id' => 149],
            [ 'measure_id' => 2, 'ingredient_id' => 149],

            [ 'measure_id' => 11, 'ingredient_id' => 150],
            [ 'measure_id' => 12, 'ingredient_id' => 150],
            [ 'measure_id' => 15, 'ingredient_id' => 150],
            [ 'measure_id' => 16, 'ingredient_id' => 150],
            [ 'measure_id' => 1, 'ingredient_id' => 150],
            [ 'measure_id' => 2, 'ingredient_id' => 150],
            [ 'measure_id' => 18, 'ingredient_id' => 150],
            [ 'measure_id' => 19, 'ingredient_id' => 150],
            [ 'measure_id' => 5, 'ingredient_id' => 150],

            [ 'measure_id' => 11, 'ingredient_id' => 151],
            [ 'measure_id' => 12, 'ingredient_id' => 151],
            [ 'measure_id' => 15, 'ingredient_id' => 151],

            [ 'measure_id' => 11, 'ingredient_id' => 152],
            [ 'measure_id' => 12, 'ingredient_id' => 152],
            [ 'measure_id' => 15, 'ingredient_id' => 152],

            [ 'measure_id' => 11, 'ingredient_id' => 153],
            [ 'measure_id' => 12, 'ingredient_id' => 153],
            [ 'measure_id' => 15, 'ingredient_id' => 153],

            [ 'measure_id' => 11, 'ingredient_id' => 154],
            [ 'measure_id' => 12, 'ingredient_id' => 154],
            [ 'measure_id' => 17, 'ingredient_id' => 154],
            [ 'measure_id' => 15, 'ingredient_id' => 154],

            [ 'measure_id' => 11, 'ingredient_id' => 155],
            [ 'measure_id' => 12, 'ingredient_id' => 155],
            [ 'measure_id' => 15, 'ingredient_id' => 155],
            [ 'measure_id' => 5, 'ingredient_id' => 155],

            [ 'measure_id' => 11, 'ingredient_id' => 156],
            [ 'measure_id' => 12, 'ingredient_id' => 156],
            [ 'measure_id' => 15, 'ingredient_id' => 156],

            [ 'measure_id' => 11, 'ingredient_id' => 157],
            [ 'measure_id' => 12, 'ingredient_id' => 157],
            [ 'measure_id' => 15, 'ingredient_id' => 157],

            [ 'measure_id' => 1, 'ingredient_id' => 158],
            [ 'measure_id' => 15, 'ingredient_id' => 158],

            [ 'measure_id' => 11, 'ingredient_id' => 159],
            [ 'measure_id' => 12, 'ingredient_id' => 159],
            [ 'measure_id' => 15, 'ingredient_id' => 159],
            [ 'measure_id' => 16, 'ingredient_id' => 159],
            [ 'measure_id' => 1, 'ingredient_id' => 159],
            [ 'measure_id' => 2, 'ingredient_id' => 159],
            [ 'measure_id' => 18, 'ingredient_id' => 159],
            [ 'measure_id' => 19, 'ingredient_id' => 159],
            [ 'measure_id' => 5, 'ingredient_id' => 159],

            [ 'measure_id' => 13, 'ingredient_id' => 160],
            [ 'measure_id' => 14, 'ingredient_id' => 160],
            [ 'measure_id' => 15, 'ingredient_id' => 160],
            [ 'measure_id' => 1, 'ingredient_id' => 160],
            [ 'measure_id' => 2, 'ingredient_id' => 160],
            [ 'measure_id' => 5, 'ingredient_id' => 160],

            [ 'measure_id' => 11, 'ingredient_id' => 161],
            [ 'measure_id' => 12, 'ingredient_id' => 161],
            [ 'measure_id' => 15, 'ingredient_id' => 161],

            [ 'measure_id' => 11, 'ingredient_id' => 162],
            [ 'measure_id' => 12, 'ingredient_id' => 162],
            [ 'measure_id' => 15, 'ingredient_id' => 162],
            [ 'measure_id' => 5, 'ingredient_id' => 162],
            [ 'measure_id' => 1, 'ingredient_id' => 162],
            [ 'measure_id' => 2, 'ingredient_id' => 162],

            [ 'measure_id' => 11, 'ingredient_id' => 163],
            [ 'measure_id' => 12, 'ingredient_id' => 163],
            [ 'measure_id' => 15, 'ingredient_id' => 163],
            [ 'measure_id' => 5, 'ingredient_id' => 163],
            [ 'measure_id' => 1, 'ingredient_id' => 163],
            [ 'measure_id' => 2, 'ingredient_id' => 163],

            [ 'measure_id' => 1, 'ingredient_id' => 164],
            [ 'measure_id' => 15, 'ingredient_id' => 164],
            [ 'measure_id' => 13, 'ingredient_id' => 164],
            [ 'measure_id' => 14, 'ingredient_id' => 164],

            [ 'measure_id' => 1, 'ingredient_id' => 165],
            [ 'measure_id' => 15, 'ingredient_id' => 165],
            [ 'measure_id' => 13, 'ingredient_id' => 165],
            [ 'measure_id' => 14, 'ingredient_id' => 165],

            [ 'measure_id' => 11, 'ingredient_id' => 166],
            [ 'measure_id' => 12, 'ingredient_id' => 166],
            [ 'measure_id' => 15, 'ingredient_id' => 166],
            [ 'measure_id' => 5, 'ingredient_id' => 166],
            [ 'measure_id' => 1, 'ingredient_id' => 166],

            [ 'measure_id' => 11, 'ingredient_id' => 167],
            [ 'measure_id' => 12, 'ingredient_id' => 167],
            [ 'measure_id' => 15, 'ingredient_id' => 167],
            [ 'measure_id' => 16, 'ingredient_id' => 167],
            [ 'measure_id' => 1, 'ingredient_id' => 167],
            [ 'measure_id' => 2, 'ingredient_id' => 167],
            [ 'measure_id' => 18, 'ingredient_id' => 167],
            [ 'measure_id' => 19, 'ingredient_id' => 167],
            [ 'measure_id' => 5, 'ingredient_id' => 167],

            [ 'measure_id' => 11, 'ingredient_id' => 168],
            [ 'measure_id' => 12, 'ingredient_id' => 168],
            [ 'measure_id' => 15, 'ingredient_id' => 168],
            [ 'measure_id' => 16, 'ingredient_id' => 168],
            [ 'measure_id' => 1, 'ingredient_id' => 168],
            [ 'measure_id' => 2, 'ingredient_id' => 168],
            [ 'measure_id' => 18, 'ingredient_id' => 168],
            [ 'measure_id' => 19, 'ingredient_id' => 168],

            [ 'measure_id' => 11, 'ingredient_id' => 169],
            [ 'measure_id' => 12, 'ingredient_id' => 169],
            [ 'measure_id' => 15, 'ingredient_id' => 169],
            [ 'measure_id' => 18, 'ingredient_id' => 169],

            [ 'measure_id' => 11, 'ingredient_id' => 170],
            [ 'measure_id' => 12, 'ingredient_id' => 170],
            [ 'measure_id' => 15, 'ingredient_id' => 170],
            [ 'measure_id' => 18, 'ingredient_id' => 170],

            [ 'measure_id' => 11, 'ingredient_id' => 171],
            [ 'measure_id' => 12, 'ingredient_id' => 171],
            [ 'measure_id' => 15, 'ingredient_id' => 171],
            [ 'measure_id' => 1, 'ingredient_id' => 171],
            [ 'measure_id' => 2, 'ingredient_id' => 171],

            [ 'measure_id' => 11, 'ingredient_id' => 172],
            [ 'measure_id' => 12, 'ingredient_id' => 172],
            [ 'measure_id' => 17, 'ingredient_id' => 172],
            [ 'measure_id' => 15, 'ingredient_id' => 172],
            [ 'measure_id' => 20, 'ingredient_id' => 172],

            [ 'measure_id' => 11, 'ingredient_id' => 173],
            [ 'measure_id' => 12, 'ingredient_id' => 173],
            [ 'measure_id' => 15, 'ingredient_id' => 173],
            [ 'measure_id' => 1, 'ingredient_id' => 173],
            [ 'measure_id' => 2, 'ingredient_id' => 173],
            [ 'measure_id' => 5, 'ingredient_id' => 173],

            [ 'measure_id' => 11, 'ingredient_id' => 174],
            [ 'measure_id' => 12, 'ingredient_id' => 174],
            [ 'measure_id' => 17, 'ingredient_id' => 174],
            [ 'measure_id' => 15, 'ingredient_id' => 174],

            [ 'measure_id' => 17, 'ingredient_id' => 175],
            [ 'measure_id' => 15, 'ingredient_id' => 175],

            [ 'measure_id' => 11, 'ingredient_id' => 176],
            [ 'measure_id' => 12, 'ingredient_id' => 176],
            [ 'measure_id' => 15, 'ingredient_id' => 176],
            [ 'measure_id' => 1, 'ingredient_id' => 176],
            [ 'measure_id' => 2, 'ingredient_id' => 176],
            [ 'measure_id' => 13, 'ingredient_id' => 176],
            [ 'measure_id' => 14, 'ingredient_id' => 176],

            [ 'measure_id' => 11, 'ingredient_id' => 177],
            [ 'measure_id' => 12, 'ingredient_id' => 177],
            [ 'measure_id' => 15, 'ingredient_id' => 177],
            [ 'measure_id' => 1, 'ingredient_id' => 177],
            [ 'measure_id' => 2, 'ingredient_id' => 177],
            [ 'measure_id' => 13, 'ingredient_id' => 177],
            [ 'measure_id' => 14, 'ingredient_id' => 177],
            [ 'measure_id' => 16, 'ingredient_id' => 177],

            [ 'measure_id' => 11, 'ingredient_id' => 178],
            [ 'measure_id' => 12, 'ingredient_id' => 178],
            [ 'measure_id' => 17, 'ingredient_id' => 178],
            [ 'measure_id' => 20, 'ingredient_id' => 178],
        ]);
    }
}
